export const STORAGE_KEY = "focusBlocker";

export const MSG = {
  START_SESSION: "START_SESSION",
  STOP_SESSION: "STOP_SESSION",
  DELETE_SESSION: "DELETE_SESSION",
  RETRY_SYNC: "RETRY_SYNC",
  BLOCKED_ITEM: "BLOCKED_ITEM",
  GET_STATE: "GET_STATE",
  SETTINGS_UPDATED: "SETTINGS_UPDATED",
  WHITELIST_UPDATED: "WHITELIST_UPDATED",
  SCHEDULE_UPDATED: "SCHEDULE_UPDATED",
  SWITCH_USER: "SWITCH_USER",
};

export const ITEM_TYPES = {
  NOTIFICATION: "notification",
  POPUP: "popup",
  DIALOG: "dialog",
};

export const API_BASE_URL = "http://localhost:5000";
